import type { Listing } from "./supabaseClient";

export const mockListings: Listing[] = [
  {
    id: "1",
    owner_id: "demo",
    title: "Sunny Single Room near Long Street",
    city: "Cape Town",
    suburb: "Gardens",
    price_zar: 6500,
    room_type: "Single room",
    description:
      "Bright, furnished room in a shared house five minutes from Long Street. Fibre wifi, weekly cleaning of common areas, and a rooftop with table mountain views.",
    amenities: ["Wifi", "Furnished", "Water & electricity included", "Secure parking"],
    image_url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    whatsapp_number: "27821234567",
    contact_email: "host1@example.com",
    verified: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    owner_id: "demo",
    title: "Modern Studio in Sandton",
    city: "Johannesburg",
    suburb: "Sandton",
    price_zar: 9800,
    room_type: "Studio apartment",
    description:
      "Self-contained studio in a secure complex, walking distance to Sandton Gautrain station. Ideal for professionals.",
    amenities: ["Wifi", "Gym access", "24hr security", "Parking bay"],
    image_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    whatsapp_number: "27829876543",
    contact_email: "host2@example.com",
    verified: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    owner_id: "demo",
    title: "Cozy Room in Stellenbosch Commune",
    city: "Stellenbosch",
    suburb: "Die Boord",
    price_zar: 5200,
    room_type: "Shared house",
    description:
      "Room in a friendly 4-person house near campus and the town centre. Big garden, braai area, and quiet study space.",
    amenities: ["Wifi", "Garden", "Braai area", "Walking distance to town"],
    image_url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    whatsapp_number: "27831239876",
    contact_email: "host3@example.com",
    verified: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    owner_id: "demo",
    title: "Spacious Room in Hatfield",
    city: "Pretoria",
    suburb: "Hatfield",
    price_zar: 4800,
    room_type: "Single room",
    description:
      "Large room in a secure complex close to shops and public transport. Prepaid electricity, own bathroom.",
    amenities: ["Own bathroom", "Prepaid electricity", "Close to transport"],
    image_url: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80",
    whatsapp_number: "27847651234",
    contact_email: "host4@example.com",
    verified: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    owner_id: "demo",
    title: "Beachside Room in Umhlanga",
    city: "Durban",
    suburb: "Umhlanga",
    price_zar: 7200,
    room_type: "Single room",
    description:
      "Ten minute walk to the beach, in a quiet complex with pool access. Great for young professionals.",
    amenities: ["Pool access", "Furnished", "Close to beach"],
    image_url: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800&q=80",
    whatsapp_number: "27835557890",
    contact_email: "host5@example.com",
    verified: true,
    created_at: new Date().toISOString(),
  },
];
